## 추론 기반 기법과 신경망

### 신경망에서의 단어 처리

In [4]:
import numpy as np

c = np.array([[1, 0, 0, 0, 0, 0, 0]])  # (1,7)
print(c.shape)
W = np.arange(21).reshape(7,3)
print(W)
h = np.dot(c, W)
print(h.shape)
print(h)

(1, 7)
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]]
(1, 3)
[[0 1 2]]


In [5]:
class MatMul:
    def __init__(self, W):
        self.params = [W]
        self.grads = [np.zeros_like(W)]
        self.x = None

    def forward(self, x):
        W, = self.params
        out = np.dot(x, W)
        self.x = x
        return out

    def backward(self, dout):
        W, = self.params
        dx = np.dot(dout, W.T)
        dW = np.dot(self.x.T, dout)
        self.grads[0][...] = dW
        return dx

In [6]:
import sys
sys.path.append('..')
import numpy as np
from common.layers import MatMul

c = np.array([[1, 0, 0, 0, 0, 0, 0]])
W = np.arange(21).reshape(7,3)
layer = MatMul(W)
h = layer.forward(c)
print(h)

[[0 1 2]]
