## 단순한 word2vec

### CBOW 모델의 추론 처리

In [9]:
import sys
sys.path.append('..')
import numpy as np
from common.layers import MatMul


# 샘플 맥락 데이터
c0 = np.array([[1, 0, 0, 0, 0, 0, 0]])
c1 = np.array([[0, 0, 1, 0, 0, 0, 0]])

# 가중치 초기화
W_in = np.arange(1,22).reshape(7, 3)
W_out = np.ones((3, 7))

print(W_in)
print(W_out)
# 계층 생성
in_layer0 = MatMul(W_in)
in_layer1 = MatMul(W_in)
out_layer = MatMul(W_out)

# 순전파
h0 = in_layer0.forward(c0)
h1 = in_layer1.forward(c1)
print(h0)
print(h1)
h = 0.5 * (h0 + h1)
print(h)
s = out_layer.forward(h)
print(s)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]]
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
[[1 2 3]]
[[7 8 9]]
[[4. 5. 6.]]
[[15. 15. 15. 15. 15. 15. 15.]]
