### seq2seq

In [21]:
import numpy as np
id_to_char = {}
char_to_id = {}

def _update_vocab(txt):
#     print(txt)
    chars = list(txt)   # '16+75  ' => ['1','6','+','7','5',' ',' ']  ['_'+'9'+'1'+' '+' ']
                                     # [ 0 , 1 , 2,  3,  4,  5 ,       6,   7] 
#     print(chars)
    for i, char in enumerate(chars):
        if char not in char_to_id:
            tmp_id = len(char_to_id)
            char_to_id[char] = tmp_id
            id_to_char[tmp_id] = char

questions = []
answers = []
i=0
for line in open("../dataset/addition.txt", 'r'):
#     print(line)
    idx = line.find('_')
#     print(idx)
#     print(line[:idx])

    questions.append(line[:idx])
#     print(questions)
#     print(line[idx:-1])
    answers.append(line[idx:-1])
#     print(answers)
    
  
#     i += 1
#     if i >= 10:
#         break
        
# print(questions)   
# print(answers)

# print(len(questions))   
# print(len(answers))

    # 어휘 사전 생성
for i in range(len(questions)):
    q, a = questions[i], answers[i]
    _update_vocab(q)
    _update_vocab(a)

# print(char_to_id)
# print(id_to_char)

print(len(questions))
print(len(questions[0]))
print(len(answers[0]))

x = np.zeros((len(questions), len(questions[0])), dtype=np.int)
t = np.zeros((len(answers), len(answers[0])), dtype=np.int)

print(x.shape)
print(t.shape)

for i, sentence in enumerate(questions):
    x[i] = [char_to_id[c] for c in list(sentence)]
for i, sentence in enumerate(answers):
    t[i] = [char_to_id[c] for c in list(sentence)]
    
print(x[0])
print(t[0])

seed=3
indices = np.arange(len(x))
print(indices)
if seed is not None:
    np.random.seed(seed)
np.random.shuffle(indices)
print(indices)
x = x[indices]
t = t[indices]

print(x[0])
print(t[0])

split_at = len(x) - len(x) // 10
print(split_at)
(x_train, x_test) = x[:split_at], x[split_at:]
(t_train, t_test) = t[:split_at], t[split_at:]

print(x_train.shape)
print(x_test.shape)

50000
7
5
(50000, 7)
(50000, 5)
[0 1 2 3 4 5 5]
[6 7 0 5 5]
[    0     1     2 ... 49997 49998 49999]
[35437 16296 23122 ... 11513  1688  5994]
[12  0 12  2 10 11  7]
[ 6 11  9 10  5]
45000
(45000, 7)
(5000, 7)


C:\Users\jikim\AppData\Local\Temp/ipykernel_448/4212564185.py:55: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.zeros((len(questions), len(questions[0])), dtype=np.int)
C:\Users\jikim\AppData\Local\Temp/ipykernel_448/4212564185.py:56: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current u

In [ ]:
# coding: utf-8
import sys
sys.path.append('..')
from dataset import sequence


(x_train, t_train), (x_test, t_test) = \
    sequence.load_data('addition.txt', seed=1984)
char_to_id, id_to_char = sequence.get_vocab()

print(char_to_id)
print(x_train.shape, t_train.shape)
print(x_test.shape, t_test.shape)
# (45000, 7) (45000, 5)
# (5000, 7) (5000, 5)

print(x_train[0])
print(t_train[0])
# [ 3  0  2  0  0 11  5]
# [ 6  0 11  7  5]

print(''.join([id_to_char[c] for c in x_train[0]]))
print(''.join([id_to_char[c] for c in t_train[0]]))
# 71+118
# _189