# 수학과 파이썬 복습

## 백터와 행렬

In [6]:
import numpy as np

l1 = [1,2,3]
print(type(l1))
print(l1.__class__)
x = np.array([1, 2, 3])
print(type(x))
print(x.__class__)

<class 'list'>
<class 'list'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [7]:
x.shape

(3,)

In [8]:
x.ndim

1

In [9]:
W = np.array([[1, 2, 3], 
              [4, 5, 6]])
W.shape

(2, 3)

In [10]:
W.ndim

2

## 행렬의 원소별 연산

In [11]:
W = np.array([1, 2, 3])
X = np.array([4, 5, 6])
W + X

array([5, 7, 9])

In [12]:
W * X

array([ 4, 10, 18])

In [13]:
W = np.array([[1, 2, 3], 
              [4, 5, 6]])
X = np.array([[0, 1, 2], 
              [3, 4, 5]])
W + X

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [14]:
W * X

array([[ 0,  2,  6],
       [12, 20, 30]])

## 브로드 케스트

In [15]:
A = np.array([1, 2])
A * 10

array([10, 20])

In [16]:
A = np.array([[1, 2], 
              [3, 4]])
A * 10

array([[10, 20],
       [30, 40]])

In [17]:
A = np.array([[1, 2], 
              [3, 4]])
b = np.array([10, 20])
A * b

array([[10, 40],
       [30, 80]])

## 벡터의 내적과 행렬의 곱 

In [18]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.dot(a, b))
print(np.sum(a*b))

32
32


In [19]:
a = np.array([1, 2])
b = np.array([[1, 1, 1],
              [2, 2, 2]])
print(np.dot(a, b))

[5 5 5]


In [20]:
a = np.array([[1, 1, 1],
              [2, 2, 2]])
b = np.array([1, 2, 3])
print(np.dot(a, b))

[ 6 12]


In [21]:
A = np.array([[1, 2], 
              [3, 4]])
B = np.array([[5, 6], 
              [7, 8]])
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [22]:
A = np.array([[1, 2, 3], 
              [4, 5, 6]])
B = np.array([[1, 2], 
              [3, 4],
              [5, 6]])
np.dot(A, B)  # (2,3)(3,2)

array([[22, 28],
       [49, 64]])