In [ ]:
!pip install transformers

     |████████████████████████████████| 3.1 MB 7.6 MB/s 
     |████████████████████████████████| 59 kB 9.0 MB/s 
     |████████████████████████████████| 596 kB 85.3 MB/s 
     |████████████████████████████████| 3.3 MB 74.4 MB/s 
     |████████████████████████████████| 895 kB 77.0 MB/s 
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [1]:
from transformers import TFBertForMaskedLM

In [2]:
model = TFBertForMaskedLM.from_pretrained('bert-large-uncased')

Downloading:   0%|          | 0.00/571 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.37G [00:00<?, ?B/s]

All model checkpoint layers were used when initializing TFBertForMaskedLM.

All the layers of TFBertForMaskedLM were initialized from the model checkpoint at bert-large-uncased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForMaskedLM for predictions without further training.


In [3]:
from transformers import AutoTokenizer

In [ ]:
tokenizer = AutoTokenizer.from_pretrained("bert-large-uncased")

Downloading:   0%|          | 0.00/28.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/226k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/455k [00:00<?, ?B/s]

In [ ]:
inputs = tokenizer('Soccer is a really fun [MASK].', return_tensors='tf')

In [ ]:
tokenizer.cls_token_id

101

In [ ]:
tokenizer.sep_token_id

102

In [ ]:
tokenizer.mask_token_id

103

In [ ]:
inputs

{'input_ids': <tf.Tensor: shape=(1, 9), dtype=int32, numpy=
array([[ 101, 4715, 2003, 1037, 2428, 4569,  103, 1012,  102]],
      dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(1, 9), dtype=int32, numpy=array([[0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 9), dtype=int32, numpy=array([[1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>}

In [ ]:
print(inputs['input_ids'])

tf.Tensor([[ 101 4715 2003 1037 2428 4569  103 1012  102]], shape=(1, 9), dtype=int32)


In [ ]:
print(inputs['token_type_ids'])

tf.Tensor([[0 0 0 0 0 0 0 0 0]], shape=(1, 9), dtype=int32)


In [ ]:
print(inputs['attention_mask'])

tf.Tensor([[1 1 1 1 1 1 1 1 1]], shape=(1, 9), dtype=int32)


In [ ]:
from transformers import FillMaskPipeline
pip = FillMaskPipeline(model=model, tokenizer=tokenizer)

In [ ]:
pip('Soccer is a really fun [MASK].')

[{'score': 0.762112021446228,
  'sequence': 'soccer is a really fun sport.',
  'token': 4368,
  'token_str': 'sport'},
 {'score': 0.2034197747707367,
  'sequence': 'soccer is a really fun game.',
  'token': 2208,
  'token_str': 'game'},
 {'score': 0.012208552099764347,
  'sequence': 'soccer is a really fun thing.',
  'token': 2518,
  'token_str': 'thing'},
 {'score': 0.0018630230333656073,
  'sequence': 'soccer is a really fun activity.',
  'token': 4023,
  'token_str': 'activity'},
 {'score': 0.001335485139861703,
  'sequence': 'soccer is a really fun field.',
  'token': 2492,
  'token_str': 'field'}]

In [ ]:
pip('The Avengers is a really fun [MASK].')

[{'score': 0.2562903165817261,
  'sequence': 'the avengers is a really fun show.',
  'token': 2265,
  'token_str': 'show'},
 {'score': 0.1728411316871643,
  'sequence': 'the avengers is a really fun movie.',
  'token': 3185,
  'token_str': 'movie'},
 {'score': 0.11107689887285233,
  'sequence': 'the avengers is a really fun story.',
  'token': 2466,
  'token_str': 'story'},
 {'score': 0.07248972356319427,
  'sequence': 'the avengers is a really fun series.',
  'token': 2186,
  'token_str': 'series'},
 {'score': 0.07046619802713394,
  'sequence': 'the avengers is a really fun film.',
  'token': 2143,
  'token_str': 'film'}]

In [ ]:
pip('I went to [MASK] this morning.')

[{'score': 0.35730746388435364,
  'sequence': 'i went to work this morning.',
  'token': 2147,
  'token_str': 'work'},
 {'score': 0.23304426670074463,
  'sequence': 'i went to bed this morning.',
  'token': 2793,
  'token_str': 'bed'},
 {'score': 0.12845049798488617,
  'sequence': 'i went to school this morning.',
  'token': 2082,
  'token_str': 'school'},
 {'score': 0.062305748462677,
  'sequence': 'i went to sleep this morning.',
  'token': 3637,
  'token_str': 'sleep'},
 {'score': 0.04695260152220726,
  'sequence': 'i went to class this morning.',
  'token': 2465,
  'token_str': 'class'}]