### Embedding 계층 구현

In [1]:
import numpy as np
W = np.arange(21).reshape(7, 3)
W

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

In [2]:
W[2]

array([6, 7, 8])

In [3]:
W[5]

array([15, 16, 17])

In [4]:
X = np.array([[1,0,0,0,0,0,0]])  
h = np.dot(X, W)   # (1,7)(7,3) => (1,3)
h

array([[0, 1, 2]])

In [10]:
idx = np.argmax(X[0])
print(idx)
print(W[idx])  # W[0]    (7,3) => (3,)
print(W[idx:idx+1])  #  (7,3) => (1,3)

print(W[[idx]])  # W[[0]]

print(W[[0,2,0,4]])  #  (7,3) => (4,3)

0
[0 1 2]
[[0 1 2]]
[[0 1 2]]
[[ 0  1  2]
 [ 6  7  8]
 [ 0  1  2]
 [12 13 14]]


In [11]:
idx = np.array([1, 0, 3, 0])
W[idx]  # W[[1,0,3,0]]

array([[ 3,  4,  5],
       [ 0,  1,  2],
       [ 9, 10, 11],
       [ 0,  1,  2]])

In [12]:
class Embedding:
    def __init__(self, W):
        self.params = [W]
        self.grads = [np.zeros_like(W)]
        self.idx = None

    def forward(self, idx):
        W, = self.params
        self.idx = idx
        out = W[idx]
        return out
    
#     def backward(self, dout):
#         dW, = self.grads
#         dW[...] = 0
#         dW[self.idx] = dout
#         return None    
    
#     def backward(self, dout):
#         dW, = self.grads
#         dW[...] = 0
#         for i, word_id in enumerate(self.idx):
#             dW[word_id] += dout[i]
#         return None   
    
    def backward(self, dout):
        dW, = self.grads
        dW[...] = 0
        np.add.at(dW, self.idx, dout)
        return None    

In [15]:
idx = [3,4,5]
embed = Embedding(W)
out = embed.forward(idx)
print(W)
print(out)
print(embed.idx)
dout = np.array([[ 7, 7, 7]])
embed.backward(dout)
print(embed.grads[0])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[3, 4, 5]
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [7 7 7]
 [7 7 7]
 [7 7 7]
 [0 0 0]]


In [19]:
idx = [0,3,0,1]
embed = Embedding(W)
out = embed.forward(idx)
print(W)
print()
print(out)
print(embed.idx)
dout = np.array([[ 1, 1, 1],
                 [ 2, 2, 2],
                 [ 5, 5, 5],
                 [ 4, 4, 4]])
embed.backward(dout)
print(embed.grads[0])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]]

[[ 0  1  2]
 [ 9 10 11]
 [ 0  1  2]
 [ 3  4  5]]
[0, 3, 0, 1]
[[6 6 6]
 [4 4 4]
 [0 0 0]
 [2 2 2]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [20]:
dW = np.zeros(5)
idx = np.array([0,1,2,0])
np.add.at(dW, idx, 1)
print(dW)

[2. 1. 1. 0. 0.]
