### 다중 분류에서 이진 분류로(구현)

In [1]:
import sys
sys.path.append('..')
from common.np import *  # import numpy as np
from common.layers import Embedding, SigmoidWithLoss
import collections

class EmbeddingDot:
    def __init__(self, W):
        self.embed = Embedding(W)
        self.params = self.embed.params
        self.grads = self.embed.grads
        self.cache = None

    def forward(self, h, idx):
        target_W = self.embed.forward(idx)
        print(target_W)
        out = np.sum(target_W * h, axis=1)   # sum((2,3)*(2,3)) => (2,)

        self.cache = (h, target_W)
        return out

    def backward(self, dout):
        h, target_W = self.cache
        dout = dout.reshape(dout.shape[0], 1)

        dtarget_W = dout * h
        print(dtarget_W)
        self.embed.backward(dtarget_W)
        print(self.embed.grads[0])
        dh = dout * target_W
        return dh

In [7]:
a = np.arange(7).reshape(-1,1)
print(a)
W_out = np.repeat(a, 3, axis=1)
print(W_out)

h = np.array([[3,4,5]])   # (1,3)

idx = np.array([1])
ed = EmbeddingDot(W_out)      # (1,3)(3,1) => (1,1)  sum([[3,4,5]]*[[1,1,1]],axis=1)=>[12]

out = ed.forward(h, idx)
print(out)
print(ed.cache)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]
 [5 5 5]
 [6 6 6]]
[[1 1 1]]
[12]
(array([[3, 4, 5]]), array([[1, 1, 1]]))


In [8]:
dout = np.array([3])
dh = ed.backward(dout)
print(ed.embed.grads[0])
print("dh = ",dh)

[[ 9 12 15]]
[[ 0  0  0]
 [ 9 12 15]
 [ 0  0  0]
 [ 0  0  0]
 [ 0  0  0]
 [ 0  0  0]
 [ 0  0  0]]
[[ 0  0  0]
 [ 9 12 15]
 [ 0  0  0]
 [ 0  0  0]
 [ 0  0  0]
 [ 0  0  0]
 [ 0  0  0]]
dh =  [[3 3 3]]


In [ ]:
h = np.array([[3,4,5],
              [6,7,8]])   # (2,3)
idx = np.array([1,2])
ed = EmbeddingDot(W_out)
ed.forward(h, idx)

In [ ]:
dout = np.array([3,4])
dh = ed.backward(dout)
print(dh)

### 네거티브 샘플링의 샘플링 기법

In [30]:
import numpy as np

np.random.choice(10)

3

In [37]:
np.random.choice(10)

1

In [57]:
words = ['you','say','goodbye','I','hello','.']
np.random.choice(words)

'goodbye'

In [62]:
np.random.choice(words, size=5)

array(['hello', 'goodbye', '.', '.', 'say'], dtype='<U7')

In [81]:
np.random.choice(words, size=5, replace=False)

array(['hello', '.', 'goodbye', 'say', 'I'], dtype='<U7')

In [128]:
p = [0.5, 0.1, 0.05, 0.2, 0.05, 0.1]
np.random.choice(words, p=p)

'you'

In [129]:
p = [1000, 1010, 10]
p /= np.sum(p)
print(p)

[0.4950495 0.5       0.0049505]


In [134]:
p = [1000, 1010, 10]
new_p = np.power(p, 0.75)
new_p /= np.sum(new_p)
print(new_p)

[0.4904092  0.49408269 0.0155081 ]


In [137]:
import collections

corpus = np.array([1,2,3,4,5,2,3,4,1,1,4,2,2,2])
counts = collections.Counter()
print(len(counts))
for word_id in corpus:
    counts[word_id] += 1
    
print(len(counts))
print(counts)

0
5
Counter({2: 5, 1: 3, 4: 3, 3: 2, 5: 1})


In [138]:
GPU = False

class UnigramSampler:
    def __init__(self, corpus, power, sample_size):
        self.sample_size = sample_size
        self.vocab_size = None
        self.word_p = None

        counts = collections.Counter()
        for word_id in corpus:
            counts[word_id] += 1

        print(counts)
        
        vocab_size = len(counts)
        self.vocab_size = vocab_size

        self.word_p = np.zeros(vocab_size)
        for i in range(vocab_size):
            self.word_p[i] = counts[i]

        print(self.word_p)
        self.word_p = np.power(self.word_p, power)
        self.word_p /= np.sum(self.word_p)
        print(self.word_p)

    def get_negative_sample(self, target):
        batch_size = target.shape[0]

        if not GPU:
            negative_sample = np.zeros((batch_size, self.sample_size), dtype=np.int32)

            for i in range(batch_size):
                p = self.word_p.copy()
                target_idx = target[i]
                p[target_idx] = 0
                p /= p.sum()
                negative_sample[i, :] = np.random.choice(self.vocab_size, size=self.sample_size, replace=False, p=p)
        else:
            # GPU(cupy）로 계산할 때는 속도를 우선한다.
            # 부정적 예에 타깃이 포함될 수 있다.
            negative_sample = np.random.choice(self.vocab_size, size=(batch_size, self.sample_size),
                                               replace=True, p=self.word_p)

        return negative_sample

In [158]:
corpus = np.array([0, 1, 2, 3, 4, 1, 2, 3, 1, 1, 2])
power = 0.75
sample_size = 2

sampler = UnigramSampler(corpus, power, sample_size)
target = np.array([1, 3, 0])
negative_sample = sampler.get_negative_sample(target)
print(negative_sample)

Counter({1: 4, 2: 3, 3: 2, 0: 1, 4: 1})
[1. 4. 3. 2. 1.]
[0.11376918 0.32178782 0.25933764 0.19133618 0.11376918]
[[2 3]
 [2 1]
 [2 3]]


In [159]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.c_[a,b]
print(c)

[[1 4]
 [2 5]
 [3 6]]


### 네거티브 샘플링 구현

In [ ]:
class NegativeSamplingLoss:
    def __init__(self, W, corpus, power=0.75, sample_size=5):
        self.sample_size = sample_size
        self.sampler = UnigramSampler(corpus, power, sample_size)
        self.loss_layers = [SigmoidWithLoss() for _ in range(sample_size + 1)]
        self.embed_dot_layers = [EmbeddingDot(W) for _ in range(sample_size + 1)]

        self.params, self.grads = [], []
        for layer in self.embed_dot_layers:
            self.params += layer.params
            self.grads += layer.grads

    def forward(self, h, target):
        batch_size = target.shape[0]
        negative_sample = self.sampler.get_negative_sample(target)

        # 긍정적 예 순전파
        score = self.embed_dot_layers[0].forward(h, target)
        correct_label = np.ones(batch_size, dtype=np.int32)
        loss = self.loss_layers[0].forward(score, correct_label)

        # 부정적 예 순전파
        negative_label = np.zeros(batch_size, dtype=np.int32)
        for i in range(self.sample_size):
            negative_target = negative_sample[:, i]
            score = self.embed_dot_layers[1 + i].forward(h, negative_target)
            loss += self.loss_layers[1 + i].forward(score, negative_label)

        return loss

    def backward(self, dout=1):
        dh = 0
        for l0, l1 in zip(self.loss_layers, self.embed_dot_layers):
            dscore = l0.backward(dout)
            dh += l1.backward(dscore)

        return dh
