In [1]:
import numpy as np

A = np.array([[3,6],
              [2,3],
              [0,0],
              [0,0]])
A

array([[3, 6],
       [2, 3],
       [0, 0],
       [0, 0]])

In [2]:
U = np.dot(A , A.T)  # (4, 2)(2, 4) => (4,4)
U

array([[45, 24,  0,  0],
       [24, 13,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0]])

In [3]:
V = np.dot(A.T , A)  # (2, 4)(4, 2) => (2,2)
V

array([[13, 24],
       [24, 45]])

In [4]:
U_eigen ,U_vector= np.linalg.eig(U)
print(U_eigen)
U_vector

[57.8444102  0.1555898  0.         0.       ]


array([[ 0.8816746 , -0.47185793,  0.        ,  0.        ],
       [ 0.47185793,  0.8816746 ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [5]:
V_eigen ,V_vector = np.linalg.eig(V.T)
print(V_eigen)
print(V_vector)

[ 0.1555898 57.8444102]
[[-0.8816746  -0.47185793]
 [ 0.47185793 -0.8816746 ]]


In [6]:
import numpy as np
from numpy.linalg import svd

A = np.array([[3, -1], 
              [1, 3], 
              [1, 1]])
U, S, VT = svd(A)

In [7]:
U

array([[-4.08248290e-01,  8.94427191e-01, -1.82574186e-01],
       [-8.16496581e-01, -4.47213595e-01, -3.65148372e-01],
       [-4.08248290e-01, -1.94289029e-16,  9.12870929e-01]])

In [8]:
S

array([3.46410162, 3.16227766])

In [9]:
VT

array([[-0.70710678, -0.70710678],
       [ 0.70710678, -0.70710678]])

In [11]:
np.diag(S, 1)[:, 1:]

array([[3.46410162, 0.        ],
       [0.        , 3.16227766],
       [0.        , 0.        ]])

In [12]:
U @ np.diag(S, 1)[:, 1:] @ VT

array([[ 3., -1.],
       [ 1.,  3.],
       [ 1.,  1.]])